export const MOCK_SUGGESTIONS = [
	{ symbol: "AAPL", name: "Apple Inc." },
	{ symbol: "TSLA", name: "Tesla Inc." },
	{ symbol: "NVDA", name: "NVIDIA Corporation" },
	{ symbol: "GOOGL", name: "Alphabet Inc." },
	{ symbol: "AMZN", name: "Amazon.com Inc." },
	{ symbol: "MSFT", name: "Microsoft Corporation" },
	{ symbol: "META", name: "Meta Platforms Inc." },
	{ symbol: "BRK.B", name: "Berkshire Hathaway Inc." },
	{ symbol: "JPM", name: "JPMorgan Chase & Co." },
	{ symbol: "V", name: "Visa Inc." },
	{ symbol: "MA", name: "Mastercard Incorporated" },
	{ symbol: "UNH", name: "UnitedHealth Group Incorporated" },
	{ symbol: "HD", name: "The Home Depot Inc." },
	{ symbol: "PG", name: "Procter & Gamble Company" },
	{ symbol: "XOM", name: "Exxon Mobil Corporation" },
	{ symbol: "DIS", name: "The Walt Disney Company" },
	{ symbol: "BAC", name: "Bank of America Corporation" },
	{ symbol: "INTC", name: "Intel Corporation" },
	{ symbol: "NFLX", name: "Netflix Inc." },
	{ symbol: "CRM", name: "Salesforce Inc." },
];
